// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDerpeRJTRqb8m77uwAwlRHdoFxwXPfhFc',
    appId: '1:231663829521:web:eff745cee65e97ab1527b0',
    messagingSenderId: '231663829521',
    projectId: 'grocery-app-34c61',
    authDomain: 'grocery-app-34c61.firebaseapp.com',
    storageBucket: 'grocery-app-34c61.appspot.com',
    measurementId: 'G-K1J9DLZPE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_MQImFhj2MicsnMuJZSMWqL0O3pF2tVE',
    appId: '1:231663829521:android:dc3406ef78ba0b341527b0',
    messagingSenderId: '231663829521',
    projectId: 'grocery-app-34c61',
    storageBucket: 'grocery-app-34c61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHjE9MkRKVBjWHypy2oW66fB7HjZPx6OE',
    appId: '1:231663829521:ios:c5e14b4fa37c2a0f1527b0',
    messagingSenderId: '231663829521',
    projectId: 'grocery-app-34c61',
    storageBucket: 'grocery-app-34c61.appspot.com',
    iosClientId: '231663829521-jakj3232mdnf808mqb09ljc40cc2p2n6.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHjE9MkRKVBjWHypy2oW66fB7HjZPx6OE',
    appId: '1:231663829521:ios:876280df32c4f3ae1527b0',
    messagingSenderId: '231663829521',
    projectId: 'grocery-app-34c61',
    storageBucket: 'grocery-app-34c61.appspot.com',
    iosClientId: '231663829521-ajvdivpavpqcl06ncjkk4m3n7i1dufet.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryApp.RunnerTests',
  );
}
